### PR TITLE
Add channel/repo management

### PR DESCRIPTION
**Pull request by ddgenome**
Implemented CreateChannel and AssociateRepo command handlers using
GraphQL mutation queries.  They are strings right now because the
"schema is out of date in the client" and does not support mutation
queries.  Add CreateChannel button to PushToUnmappedRepo.

### CODE REVIEW

**Comment by ddgenome** [comment]
Pull request auto merge enabled. [atomist:enable-auto-merge]

**Comment by cdupuis** [comment]
@ddgenome before we merge this it would be good if you could take another look.

**Comment by ddgenome** [comment]
LGTM

**Comment by slimslenderslacks** [comment]
Pull request auto merged by Atomist.

* 1 approved review by @cdupuis
* 4 successful checks

**Pull request merged**
