### PR TITLE
Adding missing channelName variable to LinkSlackChannelToRepo mutation.

### PR DESCRIPTION
**Pull request by dansmithy**

### CODE REVIEW

**Comment by dansmithy** [comment]
@cdupuis Realise that types.ts is generated, but I'm unable to find which source to adjust ... is it in this repository?

**Comment by cdupuis** [comment]
@dansmithy pushed a fix.

**Comment by dansmithy** [comment]
@cdupuis Amazing - thanks! Expected the source to match the name in the types, but now I know where to look :)

**Comment by dansmithy** [comment]
@cdupuis Am I ok to merge?

**Pull request merged**
